export default function Head() {
  return (
    <>
      <title>Dhekraa App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create Dhekraa app" />
      <link rel="icon" href="/Logo_dhekraa.ico" />
    </>
  )
}
